### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by mktonycho** [maltesie/bridge#1]
Hi, I am unable to install your plugin.

Versions of software include:
Ubuntu 20.04
PyMOL 1.7.4.5
MDAnalysis 1.1.1 

Error message on PyMOL window says:
'Plugin "bridge" has been installed but initialization failed.'

Error message on Terminal says as below:
Non-ASCII character '\xc3' in file ~/PROGRAMS/pymol/modules/pmg_tk/startup/bridge/__init__.py on line 14, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details (__init__.py, line 14)
Unable to initialize plugin 'bridge' (pmg_tk.startup.bridge).

**Comment by maltesie** [comment]
Hi,

it seems that this is a problem due to the unicode encoding of the source code. I modified the source code and hope this should fix the problem, but I did not test it. This implementation of bridge is deprecated and not maintained anymore, I recommend to use bridge2, which comes with all the features of bridge and an improved standalone interface:

https://github.com/maltesie/bridge2

Hope this helps,
Malte

**Comment by maltesie** [comment]
If the suggested help did not solve the issue, please reopen the issue and I will have a look into it again.
